# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
  docker build -t $(registryName).azurecr.io/$(imageName) .
  docker login -u $(dockerId) -p $(dockerPassword) $(registryName).azurecr.io
  docker push $(dockerId).azurecr.io/$(imageName)
- script: docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


